### ISSUE TITLE
Support for other light providers

### ISSUE THREAD

**Issue by ad-m-ss** [colinodell/google-meet-hass-extension#1]
Hi @colinodell ,

I don't have HomeAssistant at home. However, I think your project is a great idea. Are you open to contributing with the addition of other light providers? I don't know which ones yet, pipedream / Zapier / ifttt sound in the back of my head.

Kind regards

**Comment by colinodell** [comment]
Hi there!

As awesome as that would be, I unfortunately don't have the need or bandwidth to implement those features, so I'd like to keep this repository focused on the current implementation.

You are welcome to fork this though and add whatever features you wish :) If you or someone else does fork this, feel free to leave a link in this thread so others can find it!

**Comment by ad-m-ss** [comment]
Just to clarify: I didn't expect development from you, I understand the spirit of the project. 

I was wondering if you are open to accepting upstream changes as a pull request because it affects their implementations (replace HomeAssistant in the fork, instead of adding provider selection). Thanks for making it clear, I'll create a fork and let you know when it seems useful to the general public!
