### ISSUE TITLE
Closing tab fails to reset state. 

### ISSUE THREAD

**Issue by dlemmink** [colinodell/google-meet-hass-extension#2]
If I close the browser or close the tab, I don’t seem to get the return to the idle state. 

Can this be fixed?

**Comment by nareddyt** [comment]
It works fine for me. Closing a tab turns off the `input_boolean`

**Comment by colinodell** [comment]
Same, this has always worked for me.  I will close this for now but would be happy to reopen it if somebody can provide reproducible steps or other debug information.
